[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
on_event = ['VimEnter'] # 非遅延プラグインだと hook_post_source が効かないのでなんちゃってlazy化
hook_post_source = '''
  set background=dark
  colorscheme hybrid
'''
[[plugins]] #補完機能
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''
