#[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
on_event = ['VimEnter'] # 非遅延プラグインだと hook_post_source が効かないのでなんちゃってlazy化
hook_post_source = '''
  set t_Co=256
  set background=black
  colorscheme hybrid
'''
[[plugins]] #補完機能
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]] #括弧などを補完する機能
repo = 'cohama/lexima.vim'
hook_add = '''
'''

[[plugins]] #python用の補完プラグイン
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

#[[plugins]] #タブ補完を効かせる
#repo = 'ervandew/supertab'

[[plugins]] # pythonのシンタックスチェックプラグイン
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]] # pythonのインデントをPEP8に準拠させる
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]] # pythonのインデントを可視化
repo = 'nathanaelkane/vim-indent-guides'
on_ft = 'python'

[[plugins]] # vimでTeXを使うプラグイン
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]] # vimでTeXをタイプセットする
repo = 'thinca/vim-quickrun'
